SELECT USERS.USER_NAME, IFNULL(NUMBER_OF_REVIEWS.NUMBER_REVIEWS, 0) AS NUMBER_REVIEWS FROM bali.USERS
inner JOIN (SELECT REVIEWS.USERNAME, count(*) NUMBER_REVIEWS FROM bali.REVIEWS
    WHERE day(REVIEWS.DATE_REVIEW) = 9 AND month(REVIEWS.DATE_REVIEW) = 5
	GROUP BY REVIEWS.USERNAME) AS NUMBER_OF_REVIEWS
ON USERS.USER_NAME = NUMBER_OF_REVIEWS.USERNAME