SELECT OFFER_ID, OFFERS.USER_ID, OFFER_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK FROM Bali.OFFERS
INNER JOIN(SELECT USER_NAME, USER_ID FROM bali.USERS) AS USERS
ON OFFERS.USER_ID = USERS.USER_ID
WHERE USER_NAME = 'Artyom' AND OFFERS.CREATED_AT = '2021-05-20 20:12:32';