SELECT OFFERS.OFFER_ID, OFFERS.USER_ID, OFFER_NAME, DESCRIPTION, VENDOR_LINK, VALID_UNTIL, DISCOUNT, CREATED_AT, PHOTO_LINK FROM  bali.OFFERS
INNER JOIN(SELECT REVIEWS.OFFER_ID, count(*) NUMBER_REVIEWS FROM bali.REVIEWS GROUP BY REVIEWS.OFFER_ID) AS NUMBER_OF_REVIEWS
ON OFFERS.OFFER_ID = NUMBER_OF_REVIEWS.OFFER_ID
WHERE NUMBER_REVIEWS > 3